G91 ;(switch to relative positioning)
G1 F1200 ;(set feed rate to 20mm/min)
G1 Z1 ;(Lift up the nozzle)
G90 ;(Back to absolute positioning)
T0 ;(select base extruder)
G1 X0 Y190 F3000 ;(Get extruder and platform to the "end" position)
M104 S0 ; (turn off the extruder)
T1 ;(select color extruder)
G91 ;(switch to relative positioning)
G1 E5 F600 ;(return after long pause at feed rate 10mm/min)
G90 ;(Back to absolute positioning)
M104 S0 ; (turn off the extruder)
M140 S0 ; (cool down the bed)
M107 ;(fan off)
T0 ;(select base extruder)
