;(This file is for a My Prusa w/ Bowden mount)
;(**** end initilization commands ****)
G91 ;(switch to relative positioning)
G1 F1200 ;(set feed rate to 20mm/min)
G1 E-14.0 ;(retract more plastic)
G1 Z1 ;(Lift up the nozzle)
G90    ;(Back to absolute positioning)
G1 X0 Y190 F3000 ;(Get to extruder and platform to the "end" position)
G91 ;(switch to relative positioning)
G1 F900 ;(set feed rate to 15mm/min)
M140 S0 ; (cool down the bed degrees)
M104 S0 ; (turn off the extruder)
M107 ; (Fan off)
